config/routes.rb
Rails.application.routes.draw do

    root 'static_pages#home'
    get 'help'    => 'static_pages#help'
    get 'about'   => 'static_pages#about'
    get 'contact' => 'static_pages#contact'

    resources :posts do
        get 'history', :on => :member
    end
    resources :comments do
        get 'history', :on => :member
    end

    resources :users, except: [:new] do
        get 'show', to: 'users#show', as: 'profile', path: 'profile'
    end
    get 'new', to: 'users#new', as: 'signup', path: 'signup'

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    get 'search' => 'search#search'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  has_many :comment_histories, dependent: :destroy
  validates :comment, presence: true


  before_save :update_history

  def update_history
      unless self.new_record?
          comment = Comment.find(self.id)
          comment_history = CommentHistory.new
          comment_history.comment_id= self.id
          comment_history.comment_str = comment.comment
          comment_history.save
      end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :history]
  before_action :authenticate_user, except: [:show]
  def show
    @comment = Comment.find(params[:id])
    @post = @comment.post
  end

  # GET /posts/new
  def new
    @comment = Comment.new
  # @post.user = current_user
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    # @comment.post = Post.find(post_id)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = @comment.user
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to user_profile_path(@user), notice: 'Comment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:comment, :post_id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<div class="tab-pane fade active in" id="home">
    <table class ="table">
        <thead>
            <tr>
                <th>User</th>
                <th>Comment</th>
                <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
        <% @comments.each do |cmnt| %>
            <tr>
            <td><%= cmnt.user.name %></td>
            <td><%= cmnt.comment %></td>
            <td><%= link_to 'Show', cmnt %></td>
            <% if cmnt.user == current_user %>
                <td><%= link_to 'Edit', edit_comment_path(cmnt) %></td>
            <td><%= link_to 'Destroy', cmnt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        </tr>
    <% end %>
        </tbody>

    </table>


</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
<% if @comment.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

	<ul>
		<% @comment.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.hidden_field :post_id, :value => @comment.post.id %>
	<%= f.label :comment %>
	<br>
	<%= f.text_area :comment %>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', user_profile_path(@comment.user) %>

app/views/comments/history.html.erb
<h1>Comment History</h1>

<div class="tab-pane fade active in" id="home">
    <table class ="table">
        <thead>
            <tr>
                <th>User</th>
                <th>Comment</th>
                <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
        <% @comment.comment_histories.each do |cmnt| %>
            <tr>
            <td><%= @comment.user.name %></td>
            <td><%= cmnt.comment_str %></td>
        </tr>
    <% end %>
        </tbody>

    </table>


</div>

app/views/comments/new.html.erb
<div class="jumbotron">

	<h3>Compose new comment here</h3>

	<%= render 'form' %>

	<%= link_to 'Back', user_profile_path(@comment.user) %>
</div>

app/views/comments/show.html.erb
<div class="jumbotron">

<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<% if @comment.user == current_user %>
<%= link_to 'Edit', edit_comment_path(@comment) %> |
<% end %>
<%= link_to 'Back', user_profile_path(@comment.user) %> |

<%= link_to 'History', history_comment_path(@comment) %>
</div>

	