config/routes.rb
Rails.application.routes.draw do

    root 'static_pages#home'
    get 'help'    => 'static_pages#help'
    get 'about'   => 'static_pages#about'
    get 'contact' => 'static_pages#contact'

    resources :posts do
        get 'history', :on => :member
    end
    resources :comments do
        get 'history', :on => :member
    end

    resources :users, except: [:new] do
        get 'show', to: 'users#show', as: 'profile', path: 'profile'
    end
    get 'new', to: 'users#new', as: 'signup', path: 'signup'

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    get 'search' => 'search#search'

end

app/views/layouts/menu/_login_items.html.erb
<% if current_user %>
<li>
    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><Dropdown><%= current_user.name %><span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
        	<li>
                <li><%= link_to 'Edit', edit_user_path(current_user) %></li>
            </li>
            <li>
                <li><%= link_to 'Profile', user_profile_path(current_user) %></li>
            </li>
            <li class="divider"></li>
            <li class="divider"></li>
            <li>
                <li><%= link_to('Logout', logout_path, :method => :delete,  :data => {:confirm => 'Are you sure?'} ) %></li>
            </li>
        </ul>
    </li>
</li>
<li>
    <%= link_to(image_tag(current_user.avatar.url(:thumb), :class => 'thumb'), edit_user_path(current_user))  %>
</li>
<% else %>
  <li><%= link_to('Login', login_path)  %></li>
<% end %>

app/views/layouts/menu/_registration_items.html.erb
<% unless logged_in? %>
  <li><%= link_to 'Sign up', signup_path  %></li>
<% end %>