config/routes.rb
Rails.application.routes.draw do

    root 'static_pages#home'
    get 'help'    => 'static_pages#help'
    get 'about'   => 'static_pages#about'
    get 'contact' => 'static_pages#contact'

    resources :posts do
        get 'history', :on => :member
    end
    resources :comments do
        get 'history', :on => :member
    end

    resources :users, except: [:new] do
        get 'show', to: 'users#show', as: 'profile', path: 'profile'
    end
    get 'new', to: 'users#new', as: 'signup', path: 'signup'

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    get 'search' => 'search#search'

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  validates :title, :description, :presence => true
  validates :title, :length => {:minimum => 5}
  validates :description, :length => {:minimum => 10}
  validates :title, :uniqueness => true
      
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :post_histories, dependent: :destroy


  before_save :update_history
  def update_history
    unless self.new_record?
      post = Post.find(self.id)
      post_history = PostHistory.new
    post_history.post_id = self.id
    post_history.title = post.title
    post_history.description = post.description
    post_history.save
    end
  end
  
  def self.search(str_search)
    Post.where('title LIKE :search OR description LIKE :search', search: "%#{str_search}%")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :history]
  before_action :authenticate_user, except: [:show]
  # GET /posts
  # GET /posts.json

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @comment.post = @post
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.user = current_user
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @user = @post.user
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_profile_path(@user), notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:user_id, :title, :description, :rating)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, class: 'container form-horizontal') do |f| %>
<%= render partial: 'shared/error_messages', object: @post, as: 'active_object' %>
<fieldset>
    <div class="row form-group">
        <%= f.label :title, class: 'col-lg-2 control-label' %>
        <div class="col-lg-6">
            <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
        </div>
    </div>
    <div class="row form-group">
        <%= f.label :description, class: 'col-lg-2 control-label' %>
        <div class="col-lg-6">
            <%= f.text_area :description, class: 'form-control', placeholder: 'Description here...' %>
        </div>
    </div>
</fieldset>

<div class="form-group">
    <div class="col-lg-10 col-lg-offset-2">
        <%= f.submit "Create Post", :class => 'btn btn-primary' %>
        <button type="reset" onclick="clearInputField()" class="btn btn-default">Clear</button>
    </div>
</div>
<% end %>

app/views/posts/_posts.html.erb
<!--
<ul class="nav nav-tabs">
	<li class="active">
		<a href="#home" data-toggle="tab" aria-expanded="true">Home</a>
	</li>
	<li class="">
		<a href="#profile" data-toggle="tab" aria-expanded="false">Profile</a>
	</li>
</ul>-->

<div id="myTabContent" class="tab-content">
	<div class="tab-pane fade active in" id="home">
		<table class ="table">
			<thead>
				<tr>
					<th>User</th>
					<th>Title</th>
					<th>Description</th>
					<th>Date</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @posts.each do |post| %>
				<tr>
					<td><%= post.user.name %></td>
					<td><%= post.title %></td>
					<td><%= post.description %></td>
					<td><%= post.created_at.strftime("%d %b. %Y") %></td>
					<td><%= link_to 'Show', post %></td>
					<% if post.user == current_user %>
					<td><%= link_to 'Edit', edit_post_path(post) %></td> 
					<td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					<% end %>
				</tr>
				<% end %>
			</tbody>

		</table>
	</div>
	<!--
	<div class="tab-pane fade" id="profile">
			<p>
				Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.
				Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan
				four loko farm-to-table craft beer twee. Qui photo booth letterpress,
				commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR.
				Homo nostrud organic, assumenda labore aesthetic magna delectus mollit.
			</p>
		</div>-->
	
</div>

</div>
</div>

app/views/posts/edit.html.erb
<div class="jumbotron">
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', user_profile_path(@post.user) %>
</div>

app/views/posts/history.html.erb
<h1>Post History</h1>

<table class ="table">
    <thead>
        <tr>
            <th>User</th>
            <th>Title</th>
            <th>Description</th>
        </tr>
    </thead>

    <tbody>
    <% @post.post_histories.each do |post_history| %>
        <tr>
        <td><%= @post.user.name %></td>
        <td><%= post_history.title %></td>
        <td><%= post_history.description %></td>
    </tr>
    <% end %>
    </tbody>

</table>

app/views/posts/index.html.erb
<div class="jumbotron">
<p id="notice">
	<%= notice %>
</p>

<h1>Listing Posts</h1>

<!-- Nav tabs -->
<div class="col-md-8">
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active">
			<a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a>
		</li>
		<li role="presentation">
			<a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a>
		</li>
		<li role="presentation">
			<a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a>
		</li>
		<li role="presentation">
			<a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a>
		</li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="home">
		<%= render 'posts/posts'%>
					
		</div>
		<div role="tabpanel" class="tab-pane" id="profile">
			...
		</div>
		<div role="tabpanel" class="tab-pane" id="messages">
			...
		</div>
		<div role="tabpanel" class="tab-pane" id="settings">
			...
		</div>
		<%= link_to 'New Post', new_post_path %>
	</div>
	
</div>
</div>

app/views/posts/new.html.erb
<div class="jumbotron">

	<h3>Compose new post here</h3>

	<%= render 'form' %> 
	<%= link_to 'Back', user_profile_path(@post.user) %>
</div>

app/views/posts/show.html.erb
<div class="jumbotron">

	<p id="notice">
		<%= notice %>
	</p>

	<p>
		<strong>User:</strong>
		<%= @post.user.name %>
	</p>

	<p>
		<strong>Title:</strong>
		<%= @post.title %>
	</p>

	<p>
		<strong>Description:</strong>
		<%= @post.description %>
	</p>

	<p>
		<strong>Date:</strong>
		<%= @post.rating %>
		<small><%= @post.created_at.strftime("%d %b. %Y") %></small>
	</p>
	<% if User == current_user %>
	<%= link_to 'Edit', edit_post_path(@post) %> |
	<% end %>
	<%= link_to 'Back', user_profile_path(@post.user) %>
</div>
<div class="container">
	<%= render 'comments/comments'%>
	<%= render 'comments/form' %>
</div>