config/routes.rb
Rails.application.routes.draw do

    root 'static_pages#home'
    get 'help'    => 'static_pages#help'
    get 'about'   => 'static_pages#about'
    get 'contact' => 'static_pages#contact'

    resources :posts do
        get 'history', :on => :member
    end
    resources :comments do
        get 'history', :on => :member
    end

    resources :users, except: [:new] do
        get 'show', to: 'users#show', as: 'profile', path: 'profile'
    end
    get 'new', to: 'users#new', as: 'signup', path: 'signup'

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    get 'search' => 'search#search'

end

app/views/layouts/_footer.html.erb
<!--
<footer>
<div class="container">
<p class="text-muted">
copyright@ Ebad Gul.
ebadgul66@gmail.com
</p>
</div>
</footer>
-->

<footer class="footer-distributed">
	<div class="container">
		<div class="footer-left">

			<h3>KnowledgeStream</h3>

			<p class="footer-links">
				<a href="#">Home</a>
				<a href="#">About</a>
				<a href="#">Faq</a>
				<a href="#">Contact</a>
			</p>

			<p class="footer-company-name">
				Ebad Gul &copy; 2015
			</p>
		</div>

		<div class="footer-center">

			<div>
				<i class="fa fa-map-marker"></i>
				<p>
					<span>5 Beech Square, Lacken wood</span> waterford, Ireland
				</p>
			</div>

			<div>
				<i class="fa fa-phone"></i>
				<p>
					086 8960815
				</p>
			</div>

			<div>
				<i class="fa fa-envelope"></i>
				<p>
					<a href="mailto:support@company.com">ebadgul66@gmail.com</a>
				</p>
			</div>

		</div>

		<div class="footer-right">

			<p class="footer-company-about">
				<span>About the project</span>
				This is a Web Server Programming Project which is based on social media application.
			</p>

			<div class="footer-icons">

				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-linkedin"></i></a>
				<a href="#"><i class="fa fa-github"></i></a>

			</div>

		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", '#' %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
<div class="bs-component">
	<div class="alert alert-dismissible alert-<%= key %>">
		<button data-dismiss="alert" class="close">
			x
		</button>
		<%= value %>
	</div>
</div>
<% end %>

app/views/layouts/_navigation_bar.html.erb
<nav class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "KnowledgeStream", root_path, {:class=>"navbar-brand"}%>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="<%= path_active?(root_path) %>">
					<%= link_to "Home", root_path %>
				</li>
				<li class="<%= path_active?(help_path)%>">
					<%= link_to "Help", help_path%>
				</li>
				<li class="<%= path_active?(about_path)%>">
					<%= link_to "About", about_path %>
				</li>
			</ul>
	
			<ul class="nav navbar-nav navbar-right">
				<%= form_tag(search_path, :method => 'get', class: 'navbar-form navbar-left') do %>
					<div class="form-group">
						<%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search' %>
					</div>
					<%= submit_tag "Search", class: 'btn btn-default' %>
			<% end%>

				<%= render 'layouts/menu/registration_items' %>
				<%= render 'layouts/menu/login_items' %>

			</ul>
		</div>
	</div>
</nav>


app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
	  <meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <title>KnowledgeStream</title> 
	  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/navigation_bar' %>
		<div class='container'>
			<%= render 'layouts/messages' %>
    		<%= yield %>
    	
		</div>
		<%= render 'layouts/footer' %>
	</body>
</html>